config/routes.rb
Rails.application.routes.draw do
  resources :pokedex
  root 'pokedex#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pokedex_controller.rb
# app/controllers/pokedex_controller.rb

class PokedexController < ApplicationController
  def index
    @search_term = params[:term]
    if @search_term.present?
      pokemon_data = PokemonData.new(@search_term)
      pokemon_data = pokemon_data.execute

      if pokemon_data
        pokemon_description = PokemonDescription.new(pokemon_data['id'])
        pokemon_description = pokemon_description.execute
        @pokemon = data(pokemon_data, pokemon_description)
      else
        flash[:alert] = "Pokémon not found."
        redirect_to root_path
      end
    else
      first_pokemon_data = PokemonData.new(1)
      first_pokemon_data = first_pokemon_data.execute
      first_pokemon_description = PokemonDescription.new(1)
      first_pokemon_description = first_pokemon_description.execute

      if first_pokemon_data
        @pokemon = data(first_pokemon_data, first_pokemon_description)
      else
        flash[:alert] = "Error getting Pokémon data."
        redirect_to pokedex_path
      end
    end
  end

  def data(pokemon_data, pokemon_description)
    @pokemon = {
          name: pokemon_data['name'].capitalize,
          abilities: pokemon_data['abilities'].map { |ability| ability['ability']['name'].capitalize },
          height: pokemon_data['height'],
          weight: pokemon_data['weight'],
          types: pokemon_data['types'].map { |type| type['type']['name'].capitalize },
          image_url: pokemon_data['sprites']['other']['dream_world']['front_default'],
          locais: pokemon_data['location_area_encounters'],
          moves: pokemon_data['moves'].map { |move| move['move']['name'].capitalize },
          description: pokemon_description.nil? ? "Featureless" : pokemon_description['descriptions'][7]['description'],
          status: pokemon_data['stats'].map { |status| { name: status['stat']['name'].capitalize, base_stat: status['base_stat'] } }
        }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pokedex</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div style="margin-top: 110px;">    
      <div class="container">
        <% flash.each do |type, message| %>
          <% if type == "alert"%>
            <div class="notice notice-danger flash-message"  role="alert">
              <strong><i class="bi bi-exclamation-circle-fill"></i> <%= message %></strong>
            </div>
          <% else %>
            <div class="notice notice-info flash-message"  role="alert">
              <strong><i class="bi bi-check-circle-fill"></i></i> <%= message %></strong>
            </div>
          <% end %>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/pokedex/index.html.erb
<!-- app/views/pokedex/show.html.erb -->
<div class="pokedex">
  <div class="left-container">
    <div class="left-container__top-section">
      <div class="top-section__blue"></div>
      <div class="top-section__small-buttons">
        <div class="top-section__red"></div>
        <div class="top-section__yellow"></div>
        <div class="top-section__green"></div>
      </div>
    </div>
    <div class="left-container__main-section-container">
      <div class="left-container__main-section">
        <div class="main-section__white">
          <div class="main-section__black">
            <div class="main-screen">
              <div class="screen__header">
                <span class="poke-name"><%= @pokemon[:name] %></span>
                <span class="poke-id">#<%= @pokemon[:id] %></span>
              </div>
              <div class="screen__image">
                <img src="<%= @pokemon[:image_url] %>" class="poke-image" alt="front">
                <!-- Adicione aqui a imagem de costas se houver -->
              </div>
              <div class="screen__description">
                <div class="stats__types">
                  <% @pokemon[:types].each do |type|%>
                    <span class="poke-type <%= type.downcase %>"><%= type %></span>
                  <% end %>
                </div>
                <div class="screen__stats">
                  <p class="stats__weight">weight: <span class="poke-weight"><%= @pokemon[:weight] %></span></p>
                  <p class="stats__height">height: <span class="poke-height"><%= @pokemon[:height] %></span></p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="left-container__controllers">
          <div class="controllers__d-pad">
            <div class="d-pad__cell top"></div>
            <div class="d-pad__cell left"></div>
            <div class="d-pad__cell middle"></div>
            <div class="d-pad__cell right"></div>
            <div class="d-pad__cell bottom"></div>
          </div>
          <div class="controllers__buttons">
            <div class="buttons__button">B</div>
            <div class="buttons__button">A</div>
          </div>
        </div>
      </div>
      <div class="left-container__right">
        <div class="left-container__hinge"></div>
        <div class="left-container__hinge"></div>
      </div>
    </div>
  </div>
  <div class="right-container">
    <div class="right-container__black">
      <div class="right-container__screen">
        <strong>Moves:</strong>
        <% @pokemon[:moves].take(5).each do |move| %>
          <div><%= move %></div>
        <% end %>
        <strong>Characteristic:</strong>
        <div><%= @pokemon[:description] rescue nil %></div>
        <strong>Abilities:</strong>
        <% @pokemon[:abilities].each do |ability| %>
          <div><%= ability %></div>
        <% end %>
        <strong>Status:</strong>
        <% @pokemon[:status].each do |status| %>
          <%= status[:name] %>:
          <%= status[:base_stat]%>
          <br>
        <% end %>
      </div>
    </div>
    <div class="right-container__buttons">
      <div class="search-form">
        <%= form_tag(pokedex_index_path, method: :get, class: 'form-inline') do %>
          <div class="form-group">
            <%= text_field_tag :term, params[:term], class: 'form-control mb-2', placeholder: 'Search Pokémon...', style: "border: 3px solid black; box-shadow: inset 0 0 3px 3px rgba(0,0,0,.3);" %>
          </div>
          <%= submit_tag "", class: "top-section__blue" %>
        <% end %>
      </div>
    </div>
</div>
</div>